### ISSUE TITLE
Unable to sent email

### ISSUE THREAD

**Issue by philipsjp26** [saran-surya/two-step-auth#1]
issue is unable to sent email, from library. 

example response: 
{
  status: 404,
  mail: 'philipsjp12@gmail.com',
  success: false,
  message: 'Unable to send mail'
}

**Comment by saran-surya** [comment]
Hi @philipsjp26 ,

We do currently have a mailing limit on the package mail, Currently working around for the usage with custom mail Ids, Will be releasing a new update for custom mails, thus you can have your own mailing limit.

Thanks for the patience,
Happy Coding

**Comment by ItsMeSkink** [comment]
Hello, Happy New Year! I have been getting the same problem today in the NodeJS app.
