### ISSUE TITLE
Unable to enable less secure apps

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [saran-surya/two-step-auth#3]
[According to google's new directives less secure apps have been disabled](https://support.google.com/accounts/answer/6010255?hl=en&visit_id=637934718267173333-3124904683&p=less-secure-apps&rd=1)

**Comment by saran-surya** [comment]
Hi @Onyelaudochukwuka , Yes but the test servers should work fine, are you looking to setup a production server locally, Also are you working with flutter or node JS

**Comment by Onyelaudochukwuka** [comment]
I'm working with nodeJs
I don't intend to set Up the server locally

**Comment by saran-surya** [comment]
It is not needed, you can directly use the test server as of now. It takes care of the rest

**Comment by Onyelaudochukwuka** [comment]
ok thanks for the reply
